steps:
  - name: "Setup Buildevents"
    command: "curl -H \"Authorization: Bearer $BUILDKITE_API_TOKEN\" \"https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_ID\""
    key: buildevents-setup
  - name: ":rspec:"
    command: "./buildevents cmd $BUILDKITE_BUILD_ID $BUILDKITE_STEP_ID rspec-tests -- rspec --color specs"
    key: rspec-test
    plugins:
      docker-compose#v3.9.0:
        run: app
        env:
            - BUILDKITE_BUILD_ID
            - BUILDKITE_STEP_ID
  - wait
  - name: "Build Passed"
    command: "export $BUILD_START_TIME = curl -H \"Authorization: Bearer $BUILDKITE_API_TOKEN\" \"https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_ID/\" | jq -r .started_at"
    command: "echo $BUILD_START_TIME"
    command: "$BUILD_START_TIME= `date -d $BUILD_START_TIME +%s`"
    command: "echo $BUILD_START_TIME"
    command: "./buildevents build $BUILDKITE_BUILD_ID $BUILD_START_TIME success"
    key: build-pass
    if: build.state != "failed"
  - name: "Build Failed"
    command: "./buildevents build $BUILDKITE_BUILD_ID $BUILD_START_TIME failure"
    key: build-fail
    if: build.state == "failed"
