steps:
  - name: ":rspec: RSpec Tests"
    command: "./buildevents cmd $BUILDKITE_PIPELINE_SLUG-$BUILDKITE_BUILD_NUMBER $BUILDKITE_STEP_ID rspec-tests -- rspec --color specs"
    key: rspec-test
    plugins:
      docker-compose#v3.9.0:
        run: app
        env:
          - BUILDKITE_PIPELINE_SLUG
          - BUILDKITE_BUILD_NUMBER
          - BUILDKITE_STEP_ID
          - STEP_SPAN_ID
          - BUILDEVENT_APIKEY
  - wait
  - name: "Build Report"
    command: "scripts/build_report.sh"
    key: build-report
