steps:
  - name: "Setup Buildevents"
    command: "export BUILD_START=$(date +%s)"
    key: buildevents-setup
  - name: ":rspec:"
    command: "./buildevents cmd $BUILDKITE_BUILD_ID $BUILDKITE_STEP_ID rspec-tests -- rspec --color specs"
    key: rspec-test
    plugins:
      docker-compose#v3.9.0:
        run: app
        env:
            - BUILDKITE_BUILD_ID
            - BUILDKITE_STEP_ID
  - wait
  - name: "Build Passed"
    command: "./buildevents build $BUILDKITE_BUILD_NUMBER $BUILD_START success"
    key: build-pass
    if: build.state != "failed"
  - name: "Build Failed"
    command: "./buildevents build $BUILDKITE_BUILD_NUMBER $BUILD_START failure"
    key: build-fail
    if: build.state == "failed"
