#!/bin/bash
set -euo pipefail


export $BUILD_START_TIME=`curl -H "Authorization: Bearer $BUILDKITE_API_TOKEN\" \"https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_ID/" | jq -r .started_at`
$BUILD_START_TIME=`date -d $BUILD_START_TIME +%s`