#!/bin/bash

set -eu

#Record start time if we need to exit
curl -H "Authorization: Bearer $BUILDKITE_API_TOKEN" "https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER/" | jq
echo "curl -H \"Authorization: Bearer $BUILDKITE_API_TOKEN\" \"https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER/\" | jq"

export BUILD_START_TIME=`curl -H "Authorization: Bearer $BUILDKITE_API_TOKEN" "https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER/" | jq -r .started_at`
echo $BUILD_START_TIME
BUILD_START_TIME=`TZ=UTC date -d $BUILD_START_TIME +%s`
echo $BUILD_START_TIME

#Initiate the step
STEP_START=$(date +%s)
BUILDKITE_STEP=$BUILDKITE_STEP_KEY
echo $BUILDKITE_COMMAND
if [ "$BUILDKITE_COMMAND" = "buildkite-agent pipeline upload" ]
then
  BUILDKITE_STEP="pipeline-upload"
fi

STEP_SPAN_ID=$(echo $BUILDKITE_STEP_KEY | sum | cut -f 1 -d \ )
./buildevents step $BUILDKITE_PIPELINE_SLUG-$BUILDKITE_BUILD_NUMBER $BUILDKITE_STEP_ID $STEP_START $BUILDKITE_STEP

if [ $BUILDKITE_COMMAND_EXIT_STATUS -ne 0 ]
then
  ./buildevents build $BUILDKITE_PIPELINE_SLUG-$BUILDKITE_BUILD_NUMBER $BUILD_START_TIME failure
fi
